site_name: Sparrow Lab
site_url: https://sparrowlab.dev
site_description: Technical blog about Python, Linux and Automation
site_author: Valery Vorobyev

theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - content.code.copy
    - navigation.path

plugins:
  - search
  - awesome-pages
  - blog:
      post_date_format: yyyy-MM-dd
  - git-revision-date-localized
  - social

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vvsparrow
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/valery-vorobyev/
